name: Bug Report
description: File a report for a bug in the library, one issue per bug.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Give us a description of what went wrong. Is the library throwing serialization/deserialization errors? Is it breaking in unexpected ways, leading to weird behavior?
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What went wrong?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Next it's time for you to input some information specific to your environment, such as your operating system and .NET version. 
  - type: dropdown
    id: dotnet-version
    attributes:
      label:  What .NET version are you using?
      multiple: false
      options:
        - .NET 8.0
        - .NET 9.0 Previews
    validations:
      required: true    
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      placeholder: The operating system your bot was running on when you encountered the issue